# Generated by Django 4.2.7 on 2023-12-17 19:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='numero_serie',
        ),
        migrations.AddField(
            model_name='producto',
            name='codigo',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.datetime(2024, 12, 16, 14, 27, 15, 932592)),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
