# Generated by Django 5.0 on 2023-12-26 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0002_remove_producto_numero_serie_producto_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.datetime(2024, 12, 25, 11, 29, 28, 122637)),
        ),
    ]
