# Generated by Django 5.0 on 2024-01-16 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0014_alter_producto_fecha_vencimiento_alter_producto_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.datetime(2025, 1, 15, 10, 59, 23, 144886)),
        ),
    ]
