# Generated by Django 5.0.3 on 2024-04-04 18:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0024_alter_producto_fecha_vencimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.datetime(2025, 4, 4, 14, 12, 26, 598896)),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
